@server = http://127.0.0.1:3000

### home
GET {{server}}

###create Task
POST {{server}}/tasks
Content-Type: application/json

{
    "title": "teted title",
    "description": "Improvinog nodejs skills"
}

### get all Tasks
GET {{server}}/tasks

### get task by id
GET {{server}}/tasks/1

### delete task
DELETE {{server}}/tasks/2

### updateTask 
PATCH {{server}}/tasks?id=1&status=IN_PROGRESS

#######USER 
## sign up
POST {{server}}/auth/signup
Content-Type: application/json

{
    "username": "lremq",
    "password": "12561892"
}

#######USER 
## sign in
POST {{server}}/auth/signin
Content-Type: application/json

{
    "username": "lremq",
    "password": "12561892"
}