@server = http://127.0.0.1:3000

### home
GET {{server}}

###create Task
POST {{server}}/tasks
Content-Type: application/json

{

    "description": "Improving nodejs skills"
}

### get all Tasks
GET {{server}}/tasks

### get task by id
GET {{server}}/tasks/84fba823-f9a6-46fa-851b-e7501537a1c9

### delete task
DELETE {{server}}/tasks/1a29fba9-267c-4416-8ef2-72770a3f6897

### updateTask 
PATCH {{server}}/tasks?id=2d1e2a3d-836d-4cdc-9670-33293351e5ab&status=IN_PROGRESS
